server1:
  build: ./
  ports: 
    - "8080"

server2:
  build: ./
  ports: 
    - "8080"

server3:
  build: ./
  ports: 
    - "8080"

nginx:
  build: ./nginx
  links:
    - server1
    - server2
    - server3
  ports:
    - "8081:80"

